### ISSUE TITLE
Request for CKF.

### ISSUE THREAD

**Issue by ljgdasfhk** [sfwa/ukf#41]
Hello.
Do you have any plans to implement 3-CKF or 5-CKF.
For example as in
https://github.com/irvingzhang/KalmanFiltering
https://github.com/haransll/Lidar_Radar_Tracking_using_CKF
https://github.com/korken89/Comparison-of-UKF-CKF-EKF
https://github.com/Piyush3dB/ckf-matlab

**Comment by danieldyer** [comment]
Hi,

I don't currently have any plans to implement a CKF. From the papers I've read, it doesn't seem to offer a compelling performance advantage over the UKF for a given amount of computational resources. Also, both filters are derivative-free, so that's not a reason to choose a CKF over a UKF.

Having said that, I'd be very interested if you can link me to any research or point out an application where the CKF might have a significant advantage over the UKF.
